fix: fix typo in dirs

diff --git a/.github/workflows/generate-ref-docs.yaml b/.github/workflows/generate-ref-docs.yaml
--- a/.github/workflows/generate-ref-docs.yaml
+++ b/.github/workflows/generate-ref-docs.yaml
@@ -46,8 +46,8 @@ jobs:
       - name: Move Latest Docs to the "$temp/older" Directory (Archiving latest live release)
         run: |
           mkdir -p ${{ runner.temp }}/older/${{ env.LATEST_DOCS_VERSION }}
-          mv ./* ${{ runner.temp }}/older/${{ env.LATEST_DOCS_VERSION }}
-          mv ${{ runner.temp }}/older/${{ env.LATEST_DOCS_VERSION }}/assets ${{ runner.temp }}/assets
+          mv -v ./* ${{ runner.temp }}/older/${{ env.LATEST_DOCS_VERSION }}
+          mv -v ${{ runner.temp }}/older/${{ env.LATEST_DOCS_VERSION }}/assets ${{ runner.temp }}/assets
 
       - name: Checkout back to original branch
         run: git checkout ${{ env.REF }}
@@ -87,9 +87,12 @@ jobs:
       - name: Move the Newly Generated Docs to a Temporary Workspace
         run: |
           if [ "${{ inputs.buildsystem }}" == "gradle" ]; then
-            mv code/build/dokka/html ${{ runner.temp }}/new
+            mv -v code/build/dokka/html ${{ runner.temp }}/${{ env.NEW_DOCS_VERSION }}
           elif [ "${{ inputs.buildsystem }}" == "maven" ]; then
-            mv code/target/dokka ${{ runner.temp }}/${{ env.NEW_DOCS_VERSION }}
+            mv -v code/target/dokka ${{ runner.temp }}/${{ env.NEW_DOCS_VERSION }}
+          else
+            echo "Error: Unsupported build system"
+            exit 1
           fi
 
       - name: Checkout "gh-pages" Branch
@@ -99,9 +102,7 @@ jobs:
         run: rm -rf ./* .gradle
 
       - name: Move Newly Generated Docs to the Repository Root
-        run: |
-          mv ${{ runner.temp }}/assets ./assets
-          mv ${{ runner.temp }}/${{ env.NEW_DOCS_VERSION }}/* .
+        run: mv -v ${{ runner.temp }}/${{ env.NEW_DOCS_VERSION }}/* .
 
 #      - name: Commit and Push the Changes
 #        run: |
